services:
  - type: web
    name: baby-cry-analyser
    env: python
    buildCommand: pip install -r code/web/backend/requirements.txt
    startCommand: cd code/web/backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
